version: '3'

services:
  server:
    build:
      context: .
    restart: always
    environment:
      CERTBOT_EMAIL: "rsforbes0@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro
      - letsencrypt:/etc/letsencrypt


volumes:
  letsencrypt: