name: deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.SERVER_REPO_PATH }}
            git pull
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose --force-recreate --build up