name: deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: cd ${{ secrets.SERVER_REPO_PATH }} && git pull && echo ${{ secrets.PASSWORD }} | sudo -S docker-compose --force-recreate --build up
          debug: true