name: deploy

on: pull_request
  types: [closed]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: cd ${{ secretes.SERVER_REPO_PATH }} && git pull && echo ${{ secrets.PASSWORD }} | sudo -S docker-compose --force-recreate --build up